spring.application.name=markmywords

#h2
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/markmywords}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:3644}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
app.python-service.url=${APP_PYTHON_SERVICE_URL:http://localhost:8000}
#showing activity in console
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console


#delaying loosing connection and exiting session
#spring.datasource.url=jdbc:h2:mem:markmywords;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

#Show JPA's SQL queries
spring.jpa.show-sql=true

#the datasbase is created first for seeding
spring.jpa.defer-datasource-initialization=true
