spring.application.name=markmywords

#h2
#spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#showing activity in console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


#delaying loosing connection and exiting session
spring.datasource.url=jdbc:h2:mem:markmywords;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE 

#Show JPA's SQL queries
spring.jpa.show-sql=true
